voxpupuli/puppet-yum

.msync.yml, .rubocop.yml, .travis.yml, CHANGELOG.md, Gemfile, metadata.json, spec/spec_helper.rb
=> Modulesync 0.12.0 + Release 0.9.12

CHANGELOG.md, metadata.json
@bastelfreak @rnelson0 @nibalizer
=> Release 0.9.13

CHANGELOG.md, metadata.json
=> Release 0.9.14

CHANGELOG.md, metadata.json
Fixed issue with "puppet module install yum" unable to satisfy dependencies
=> Update changelog and version

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, .gitignore, .msync.yml, .rubocop.yml, .sync.yml, .travis.yml, CHANGELOG.md, Gemfile, metadata.json, spec/acceptance/nodesets/docker/centos-5.yml, spec/acceptance/nodesets/docker/centos-6.yml, spec/acceptance/nodesets/docker/centos-7.yml, spec/acceptance/nodesets/docker/debian-7.yml, spec/acceptance/nodesets/docker/debian-8.yml, spec/acceptance/nodesets/docker/ubuntu-12.04.yml, spec/acceptance/nodesets/docker/ubuntu-14.04.yml, spec/acceptance/nodesets/docker/ubuntu-16.04.yml, spec/acceptance/nodesets/fedora-24-x64.yml, spec/acceptance/nodesets/fedora-25-x64.yml, spec/default_facts.yml, spec/spec_helper.rb
This is needed for our Puppet4 migration https://voxpupuli.org/blog/2017/01/11/migrating-to-puppet4/
=> Modulesync 0.16.7 & Release 0.10.0

.msync.yml, .sync.yml, .travis.yml, Gemfile, metadata.json, spec/spec_helper.rb
=> Modulesync 0.17.0

.gitignore, .msync.yml, .sync.yml, .travis.yml, Gemfile, Rakefile
=> Modulesync 0.19.0

CHANGELOG.md, README.md, metadata.json
=> Release 1.0.0

.github/CONTRIBUTING.md, .msync.yml, .overcommit.yml, .rubocop.yml, .travis.yml, Gemfile, spec/defines/config_spec.rb, spec/defines/gpgkey_spec.rb, spec/defines/group_spec.rb, spec/defines/plugin_spec.rb
=> Modulesync 0.21.0

metadata.json
Update concat dependency to <5.0.0
=> Update concat dependency

manifests/plugin/versionlock.pp, spec/defines/versionlock_spec.rb
=> Support `ensure => absent` with yum::versionlock

data/os/RedHat/Amazon.yaml, metadata.json
Added Hieradata and modified `metadata.json` file for compatibility with AmazonLinux 2017.
=> Add AmazonLinux 2017 compatibility.

.github/CONTRIBUTING.md, .msync.yml, .rubocop.yml, .sync.yml, .travis.yml, Gemfile, Rakefile, spec/acceptance/nodesets/docker/debian-7.yml, spec/acceptance/nodesets/docker/debian-9.yml, spec/spec_helper.rb
=> modulesync 1.4.1

CHANGELOG.md, Gemfile, metadata.json
=> release 2.1.0

README.md, data/os/RedHat/RedHat.yaml, spec/classes/init_spec.rb
Closes: https://github.com/voxpupuli/puppet-yum/issues/76
=> Add RHEL repos and update README.

metadata.json
=> bump lowest puppet version 4.6.1->4.10.9

README.md
in accordance with our metadata.json
=> update required Puppet version in the documentation

.travis.yml, manifests/init.pp
=> replace deprecated has_key() with `in`

metadata.json
Support latest release of `puppetlabs/concat`.
=> Update concat dependency to allow puppetlabs/concat 6.x

README.md
bolt URL in documentation had incorrect protocol
=> Correct bolt URL

metadata.json
=> Add dnf tag to metadata

data/os/RedHat/Rocky.yaml, metadata.json, spec/classes/init_spec.rb
Add support for rocky linux
https://github.com/voxpupuli/puppet-yum/pull/202 + https urls instead of http
=> Add support for rocky linux

REFERENCE.md, manifests/plugin/post_transaction_actions.pp, manifests/post_transaction_action.pp
Render post_transaction_action examples correctly
=> Render post_transaction_action examples correctly

CHANGELOG.md, REFERENCE.md, metadata.json
=> Release 5.2.0

manifests/versionlock.pp
Fix examples - use integer instead of string
=> Fix examples in manifests/versionlock.pp

data/os/RedHat/VirtuozzoLinux/7.yaml
resubmit of https://github.com/voxpupuli/puppet-yum/pull/190
=> yamllint failure on VirtuozzoLinux/7.yaml - duplication of key gpgkey

CHANGELOG.md, metadata.json
=> Release 5.3.1

data/os/RedHat/CentOS/8.yaml
=> fix centos8 HA yumrepo target

spec/defines/post_transaction_action_spec.rb
=> rubocop: autofix

CHANGELOG.md, REFERENCE.md, metadata.json
=> Release 5.4.0

.github/CONTRIBUTING.md, .msync.yml, Gemfile
=> modulesync 5.3.0

data/os/RedHat/CentOS/9.yaml, metadata.json, spec/acceptance/define_versionlock_spec.rb, spec/classes/init_spec.rb
This adds the basic CentOS Stream 9 repos
N/A
=> Add CentOS Stream9 repos

data/repos/repos.yaml
This adds definitions for folks who can use RPMFusion in their environment.
N/A
=> Add RPMFusion repos

CHANGELOG.md, REFERENCE.md, metadata.json
=> Release 5.6.0

data/os/RedHat/CentOS/9.yaml
The CentOS Stream9 AppStream repo has a minor typo
N/A
=> [bugfix] typo in appstream repo

CHANGELOG.md, metadata.json
=> Release 5.6.1

CHANGELOG.md, README.md, metadata.json
=> Release 6.0.0

metadata.json
No changes in repositories in Fedora 37 release
=> add Fedora 37 support

functions/bool2num_hash_recursive.pp, manifests/init.pp, metadata.json
=> puppetlabs/stdlib: Require 9.x

metadata.json, spec/acceptance/define_group_spec.rb
=> Drop EL 7 support
