manifests/plugin/versionlock.pp
manifests/versionlock.pp
metadata.json

To avoid multiple lines when updating a version

Manage yum::versionlock with concat

---

manifests/gpgkey.pp

How to reproduce:
**hiera .yaml**
```
yum::gpgkey:
'/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6.puppet-managed':
path: '/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6.puppet-managed'
ensure: 'present'
source: puppet:///modules/yum/gpgkey/RPM-GPG-KEY-EPEL-6
```
manifest.pp:
```
$yum_gpgkeys = hiera_hash("yum::gpgkey")
create_resources("yum::gpgkey", $yum_gpgkeys)
```

Bug: Puppet creates empty key files when using Hiera and create_resources()

---

.fixtures.yml

I was getting an error
```
Puppet::PreformattedError:
Evaluation Error: Error while evaluating a Function Call, Could
not find class ::yum for aiadm101.cern.ch at line 1:1 on node
aiadm101.cern.ch
```

Correct format of fixtures file.

---

README.md
manifests/init.pp
manifests/params.pp
spec/classes/basic_spec.rb

Add parameter clean_old_kernels that can be used to disable cleaning up of old kernels when installonly_limit is changed

Add parameter clean_old_kernels

---

manifests/config.pp
spec/defines/config_spec.rb

Wrapping `$ensure` in single quotes allows comma separated values.
voxpupuli/puppet-yum#21

Comma separated values

---

manifests/config.pp
spec/defines/basic_config_spec.rb

@bastelfreak 
Enable comma separated values in yum::config, basically same change as for puppet 4

Comma seperated values puppet3

---

manifests/versionlock.pp
spec/defines/versionlock_spec.rb
types/versionlockstring.pp

This commit locks down the versionlock defined type using a more
comprehensive regular expression, storing the Pattern in a type alias.
Previously two simple regular expressions were used, but they allowed
for invalid inputs with wildcards that spanned multiple fields--
wildcards are only permitted within an individual field.
Fixes #35

Be more strict about versionlock strings

---

manifests/config.pp
spec/defines/config_spec.rb

According to the man page for `yum.conf(5)`, `[main]` is the only valid
section for global Yum config options.  All other section names refer to
individual repositories.  This commit removes the `section` parameter in
the `yum::config` defined type, hard-coding it to `main`.

Remove `section` parameter from `yum::config`

---

spec/defines/versionlock_spec.rb
types/versionlockstring.pp

Case example:
```
1:java-1.7.0-openjdk-1.7.0.121-2.6.8.0.el7_3.x86_64
```
Is a valid `E:N-V-R` for yum versionlock.
In this case the release is as defined in
Yum::VersionlockString is `2.6.8.0`  and so
dots must be permitted.

Versionlock release string may contain dots

---

README.md
data/repos.yaml
hiera.yaml
spec/classes/init_spec.rb

This adds the data required to enable EPEL via the `managed_yumrepos`
parameter.

Add module data for EPEL

---

CHANGELOG.md
Rakefile
metadata.json

Prepare release 2.0.0

---

manifests/versionlock.pp

Contain the versionlock subclass to help with ordering around package resources

---

CHANGELOG.md
metadata.json

Release 2.0.2

---

data/repos.yaml

Puppet's `yumrepo` type's `name` parameter maps to the `repositoryid`
attribute of concrete Yum repos, whereas the `yumrepo` type's `descr`
parameter maps to the concrete `name` attribute.  Prior to this commit
the two were confused in the EPEL repository data, causing parse errors.
This commit corrects this error, changing the `name` parameter keys to
`descr`.
Fixes #53

Fix EPEL repo IDs

---

README.md

The documentation is incorrect for `mirrorlist` since the knockout prefix creates a blank value which will fail type validation:
```
Error: Failed to apply catalog: Parameter mirrorlist failed on Yumrepo[base]: Validate method failed for class mirrorlist: Must be a valid URL at /etc/puppetlabs/code/environments/labv5/modules/yum/manifests/init.pp:131
```

Fix documentation instructions for mirrorlist

---

hiera.yaml
metadata.json

This PR fixes #77 .
Currently our required Puppet version according to metadata.json is at least 4.10.9 which means that Hiera 5 is always available.

migrate Hiera 4 to Hiera 5

---

data/os/RedHat/Amazon.yaml

Remove the Amazon Linux default repository parameters fastestmirror_enabled and report_instanceid.
While report_instanceid is functional, fastestmirror_enabled is not functional. Neither parameter is supported by the Puppet Yumrepo type.
Puppetlabs has been approached (in https://tickets.puppetlabs.com/browse/PUP-8730) to add support for these parameters, however a decision has been made not to do this and instead to modify the Yumrepo type in Puppet 6 to allow for arbitrary parameters (https://tickets.puppetlabs.com/browse/PUP-8904).
Until such time as this issue is addressed in Puppet it is not possible to define these parameters to maintain parity with upstream and therefore they should be removed from this module. Otherwise the Default OS Repo functionality for Amazon Linux in this …

Remove fastestmirror_enabled and report_instanceid parameters

---

README.md
manifests/clean.pp
manifests/plugin/versionlock.pp
spec/acceptance/define_versionlock_spec.rb
spec/defines/versionlock_spec.rb

Currently when a versionlock entry is updated it has the unfortunate
problem that the cached yum repository metadata only contains
the previous locked files.
The class `yum::plugin::versionlock` now has a new option `clean`
defaulting to `false`. If true a `yum clean all` will exectuted
after the versionlock file is updated.
A new class `yum::clean` is added as it may be sensible
for some other operations to do the same.

Clean yum metadata after versionlock file update

---

README.md
data/common.yaml
data/os/RedHat.yaml
manifests/init.pp
metadata.json
spec/classes/init_spec.rb

Add the EPEL GPG key for EL6 and EL7, and adding the logic to automatically include GPG Keys from the yum::gpgkeys hash, including tests and some basic docs.
Fixes #95

Fixes #95 Add EPEL GPG Key and logic to handle yum::gpgkeys

---

manifests/gpgkey.pp

The previous command created (or modified existing) .gpg files under /root/, even on --noop runs.

Don't litter /root/ with GPG-related files.

---

README.md
tasks/init.json
tasks/init.rb

This adds a puppet task called yum that allows to run a yum update or
upgrade through bolt.
It also has a quiet parameter to run without output.
Fixes #107

(#107) YUM update puppet task support

---

manifests/gpgkey.pp
spec/defines/gpgkey_spec.rb

`ensure => present` for ``yum::gpgkey`` is inconsistent with newer versions of GPG (presumably starting with 2.2, but I have a limited sample size). Change has occured between 2.0.9 and 2.2.5.
```
hawking:~ # gpg --version
gpg (GnuPG) 2.2.5
libgcrypt 1.8.2
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Home: /root/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
``` …

Correctly calculate rpmname for all gpg versions

---

README.md
manifests/group.pp
spec/defines/group_spec.rb

We want to install a group using an extra repository not enabled by
default.
We can now enable that extra repository during group install using the
`install_options` parameter.
E.g.:
yum::group {
'mate-desktop-environment':
ensure          => present,
install_options => ['--enablerepo=epel']
}

Add optional parameters to groupinstall

---

data/common.yaml
manifests/init.pp

Puppet 6 issue and knockout_prefix problem

---

README.md
tasks/init.json

The current task expect Puppet agent installed on the remote.
If it is missing on the remote we get the following error message :
```
bolt task run yum action=update --nodes node1 --modulepath ./modules
Started on node1...
Failed on node1:
The task failed with exit code 126:
bash: /tmp/594417c7-c1ef-4956-b9ba-b07933580923/init.rb: /opt/puppetlabs/puppet/bin/ruby: bad interpreter: Aucun fichier ou dossier de ce type
{
}
Failed on 1 node: node1
Ran on 1 node in 0.81 seconds
```
This PR add the expression of the requirement in bolt. This should permit to get a nicer error message:
```
bolt task run yum action=update --nodes node1 --modulepath ./modules
Started on node1...
Failed on node1:
No suitable implementation of yum for node1
Failed on 1 node: node1
Ran on 1 node in 0.15 seconds
```

add requirement expression in metadata of task

---

manifests/init.pp
manifests/plugin.pp

access `os` facts thru the global `facts` variable
I've seen test failures in dependent modules, so I'd like to plug that hole!

use $facts when accessing os fact

---

manifests/init.pp

Since we're not doing any dynamic creation of potentially unknown
resources, we want to use `yumrepo` and `yum::config` directly, rather
than going thru `Resource`
none; only my confusion when reading the code.

instantiate yumrepo & yum::config directly

---

manifests/versionlock.pp

The plugin class `yum::plugin::versionlock` should not be `contain`ed
from every instance of the `yum::versionlock` defined type. Doing so
makes it impossible to use the type in multiple dependent
classes/profiles. `contain` implies that the resource 'owns' the plugin.
Using `require` should be just as effective at solving #43 without
introducing dependency cycles.
With `contain`...
```puppet
class profile::foo {
yum::versionlock { '0:bash-4.1.2-9.el6_2.*':}
}
class profile::bar {
yum::versionlock { '2:vim-enhanced-7.4.629-6.el7.x86_64':}
}
include profile::foo
include profile::bar
Class['profile::foo'] -> Class['profile::bar']
```
fails with
```
Error: Found 1 dependency cycle:
(Augeas[yum.conf_plugins] => Yum::Config[plugins] => Yum::Plugin[versionlock] => …
```

`require` (not `contain`) yum::plugin::versionlock

---

data/os/RedHat/VirtuozzoLinux/6.yaml
data/os/RedHat/VirtuozzoLinux/7.yaml
metadata.json
spec/classes/init_spec.rb

`facter` 3.14 adds support for `os.name` *VirtuozzoLinux* (https://puppet.com/docs/puppet/latest/release_notes_facter.html). This means `os.name` won't resolve to *RedHat* anymore.

add 'VirtuozzoLinux' support

---

README.md
data/os/RedHat/Fedora.yaml
manifests/init.pp
metadata.json
spec/classes/init_spec.rb

* Adds support for overriding the utils package for DNF-based distributions where the utils package is `dnf-utils`
* Adds basic support for Fedora 29/30, by setting the utils package to `dnf-utils` in os-specific module data.
Related to #139

Support for DNF-based distros, and Fedora defaults

---

data/os/RedHat/Amazon/8.yaml
data/os/RedHat/CentOS/8.yaml
data/os/RedHat/RedHat/8.yaml
data/os/RedHat/VirtuozzoLinux/8.yaml
metadata.json
spec/classes/init_spec.rb

Updating -utils package for RHEL 8
N/A

Updated utils package for RHEL 8

---

manifests/group.pp
spec/defines/group_spec.rb

Update `yum::group` to have additional state of `latest` that will ensure all mandatory packages of a group are always installed.
When a mandatory package is not installed for a group that is installed it will be prefixed with `+`. Without this change any changes to a mandatory package list would never get installed without manual intervention.
We use package groups to ensure baseline package list and it's much faster to apply one package group than dozens of individual Package resources.

Support ensuring all yum group packages are installed

---

data/os/RedHat/Amazon/8.yaml
data/os/RedHat/CentOS/8.yaml
data/os/RedHat/RedHat/8.yaml
data/os/RedHat/VirtuozzoLinux/8.yaml
spec/classes/init_spec.rb

This PR will ensure that yum-utils gets installed on CentOS as unfortunately even on CentOS 8 this is still provided by yum-utils.
Fixes #158

Fedora/CentOS8: Ensure yum-utils/dnf-utils are present

---

data/common.yaml
data/os/RedHat/CentOS.yaml
data/os/RedHat/CentOS/6.yaml
data/os/RedHat/CentOS/7.yaml
data/repos.yaml
hiera.yaml

This PR fixes an inconsistency in the hiera.yaml indentation. Indentation should always be a consistent number of whitespaces.
I choose 2 whitespaces since it matches the general puppet [style guide](https://puppet.com/docs/puppet/latest/style_guide.html#spacing-indentation-and-whitespace). 
n/a

Fix yaml indentation inconsistency

---

lib/facter/yum_reboot_required.rb
lib/facter/yum_updates.rb
tasks/init.json
tasks/init.rb

This PR add a bunch of facts similar to the ones provided by the [apt module](https://github.com/puppetlabs/puppetlabs-apt/blob/master/lib/facter/apt_updates.rb):
* `yum_has_updates` — `Boolean` indicating if updates are available;
* `yum_package_updates` — `Array[String]` list of upgradable packages;
* `yum_updates` — `Integer` number of upgradable packages;
* `yum_reboot_required` — `Boolean` indicating if the systems needs to be rebooted.
e.g.
```
% facter yum_has_updates yum_package_updates yum_reboot_required yum_updates
yum_has_updates => true
yum_package_updates => [
"puppet-agent.x86_64"
]
yum_reboot_required => true
yum_updates => 1
```
```
% facter yum_has_updates yum_package_updates yum_reboot_required yum_updates
yum_has_updates => false
yum_package_updates => [] …
```

Add support for yum facts (similar to the apt ones)

---

data/os/RedHat.yaml

This PR will add the EPEL8 gpg key for RHEL

Add gpg key for EPEL8

---

REFERENCE.md
functions/bool2num_hash_recursive.pp
manifests/init.pp
types/versionlockstring.pp

REFERENCE.md was being created such that rendering was broken. In particular
it contained lots of nested code blocks of yaml inside puppet examples and
the 2nd half of the document was not being rendered at all.
Luckily rendering yaml as puppet code does not look bad.

Remove nested code blocks from string docs

---

README.md
REFERENCE.md
manifests/versionlock.pp
spec/defines/versionlock_spec.rb
spec/type_aliases/yum_rpmarch_spec.rb
spec/type_aliases/yum_rpmname_spec.rb
spec/type_aliases/yum_rpmrelease_spec.rb
spec/type_aliases/yum_rpmversion_spec.rb
types/rpmarch.pp
types/rpmname.pp
types/rpmrelease.pp
types/rpmversion.pp

Support paramatized yum::versionlock
Motivated by the change of format to the versionlock file with DNF systems
change `yum::versionlock` so it supports parameters `version`,
`release`, `epoch` and `arch`. If version is specified the namevar is now the package name.
So on a DNF based systemd (e.g CentOS 8) the following must be used.
```puppet
yum::versionlock{'bash':
version => '3.4',
}
```
results in a version lock of on a dnf based system
```
bash-0:3.4-*
```
and on a yum based system of
```
0:bash-3.4-*
```
A fuller example with all parameters set.
```puppet
yum::versionlock{'bash':
version  => '5.4',
release  => 'alpha-rc3',
epoch    => 8,
arch     => 'noarch'
}
```
results in a version lock on a DNF based system of
```
bash-8:5.4-alpha-rc3.noarch
```
The same mechanism on YUM based …

Support paramatized yum::versionlock

---

.sync.yml
.travis.yml
spec/acceptance/define_versionlock_spec.rb

Correct acceptence tests for DNF (8) system
Use the new versionlock specification from #169 on CentOS 8.
Also test the new specification on 7 and 8 also.
Finally test that if samba-devel is filtered at
an impossible version it is no longer available.
For the yum case probably assumes that samba-devel is not installed.

Enable and add CentOS 8 accept tests

---

types/rpmrelease.pp

There were two start of string characters in a regex, `\A` and `^`. Reduce it to one which
is quite enough.

De-duplicate start of string match character

---

lib/facter/yum_updates.rb
spec/unit/facter/yum_package_updates_spec.rb

The `yum list updates` command outputs diagnostic messages and then the actual available updates both on stdout.  Depending on the installed yum plugins, a variable number of diagnostic lines are emitted, and the output is always formatted for humans, making it non-trivial to distinguish useless and relevant lines.
Instead of ignoring the first line, match each line with a pattern matching the following fields:
- package: The name of the package for which an update is available, they are in the format `<package-name>.<architecture>`;
- available_version: The version of the package available for update, ensure it starts with a digit;
- repository: The repository containing the update
These fields are separated by a variable amount of space.  When a line match this pattern, consider the …

Improve extraction of available updates

---

REFERENCE.md
manifests/versionlock.pp
spec/defines/versionlock_spec.rb

Previously it was possible to use an arch of `undef` which
produced versionlock files for both yum and dnf that would
never match a package.
Change the default to `*` so versionlock lines always end in
`.*` unless an arch is specified in which case it is
`.x86_64` for instance.

versionlock must specify at least .* for arch.

---

spec/classes/init_spec.rb
spec/defines/config_spec.rb
spec/defines/gpgkey_spec.rb
spec/defines/versionlock_spec.rb

Rather than:
```ruby
it { is_expected.to raise_error(Puppet::PreformattedError,
`%r{Package name must be formatted as Yum::RpmName, not 'String'}
)
}
```
use
```ruby
it { is_expected.to compile.and_raise_error(
%r{Package name must be formatted as Yum::RpmName, not 'String'}
)}
```

Use simpler code for tests for expected failures

---

.github/SECURITY.md
.msync.yml
.rubocop.yml
.travis.yml
Gemfile
functions/bool2num_hash_recursive.pp
manifests/clean.pp
manifests/config.pp
manifests/gpgkey.pp
manifests/group.pp
manifests/init.pp
manifests/install.pp
manifests/plugin/versionlock.pp
manifests/versionlock.pp
spec/defines/versionlock_spec.rb
spec/spec_helper_acceptance.rb

modulesync 3.0.0 & puppet-lint updates

---

manifests/versionlock.pp
types/rpmarch.pp
types/versionlockstring.pp

Resolve puppet-lint reported issues.
I like to run puppet-lint against my whole code tree every so often and it flagged these items.

Resolve puppet-lint

---

manifests/plugin/versionlock.pp
spec/acceptance/define_versionlock_spec.rb

RHEL/CentOS 8 does not provide yum-plugin-versionlock, this patch sets the package prefix for the versionlock plugin package depending on the os release major version
fixes #197

fix package name for yum plugin versionlock on RHEL/CentOS 8

---

data/os/RedHat/AlmaLinux.yaml
metadata.json
spec/classes/init_spec.rb

Added support for AlmaLinux 8

---

README.md
REFERENCE.md
manifests/plugin/post_transaction_actions.pp
manifests/post_transaction_action.pp
spec/acceptance/post_transaction_actions_spec.rb
spec/classes/plugin_post_transaction_actions_spec.rb
spec/defines/post_transaction_action_spec.rb
spec/type_aliases/yum_rpmnameglob_spec.rb
types/rpmnameglob.pp

A new type is added to install the post-transaction_action plugin
for YUM or DNF.
```puppet
yum::post_transaction_action{'touch_file':
key     => 'openssh-*',
command => 'touch /tmp/openssh-package-updated',
}
```
will touch a file every time an openssh package is installed
removed or upgraded.
https://dnf-plugins-core.readthedocs.io/en/latest/post-transaction-actions.html

New type yum::post_transaction_action

---

spec/type_aliases/yum_rpmarch_spec.rb
types/rpmarch.pp

Add aarch64 as a possible for architecture of a versionlock.
Currently
```puppet
yum::versionlock{['glog','glog-devel']:
ensure  => present,
version => '0.3.5',
release => '4.el8',
arch    => 'aarch64'
}
```
fails despite:
```bash
rpm -q --queryformat '%{name} %{version} %{release} %{arch}\n' glog
glog 0.3.5 4.el8 aarch64
```

Allow arch aarch64 in yum::versionlock

---

data/os/RedHat/AlmaLinux.yaml
spec/classes/init_spec.rb

sync with upstream AlmaLinux repository set
AlmaLinux now provides additional repositories - ha, plus and resilient storage
Previously, several repositories have been misconfigured, since descr is a required field
Considering that yumrepo will finally implement target soon, fix targets as well

sync with upstream AlmaLinux repository set

---

data/repos/RedHat/8.yaml

failovermethod parameter doesn't exist in dnf
`Invalid configuration value: failovermethod=priority in /etc/yum.repos.d/epel.repo; Configuration: OptionBinding with id "failovermethod" does not exist
`

failovermethod parameter doesn't exist in dnf

---

data/repos/RedHat/8.yaml

fix wrong repo names that lead to 404 errors
it should be epel-modular-$releasever instead of
modular-epel$releasever
Fixes #246

Fix epel-modular repo names

---

data/package_provider/dnf.yaml
data/package_provider/yum.yaml
hiera.yaml
manifests/plugin/versionlock.pp
manifests/post_transaction_action.pp
spec/classes/plugin_versionlock_spec.rb

The versionlock file used by the module actually points to the wrong place on `dnf` based systems.  This should fix that up and add a parameter to make it easier to set locks/actions.
n/a

Finish out dnf path for versionlock.

---

README.md
manifests/install.pp

Add the option to reinstall a package if the rpm verify fails for the installed package.
None

Add `require_verify` option to install.pp

---

data/common.yaml
data/package_provider/yum.yaml
spec/defines/post_transaction_action_spec.rb
spec/defines/versionlock_spec.rb

With the changes in https://github.com/voxpupuli/puppet-yum/pull/253 `yum::versionlock` was failing for cases where
`$facts['package_provider]` was unset which is typically the case for rspec compilations.
Default `yum::versionlock::path` to the existing yum location.

Avoid assumption that package_provider is set

---

manifests/init.pp
spec/classes/init_spec.rb

With the support for defining repos, it is helpful to have an easy way to purge unmanaged repos.
N/A

Permit easily purging unmanaged repos

---

manifests/config.pp
manifests/init.pp
spec/classes/init_spec.rb
spec/defines/config_spec.rb

I would like the `proxy_password` config not be leaked in the puppet log.  This PR address this issue by disabling the `show_diff` when the given config is of type `Sensitive`
```
class example {
$secret = Sensitive('mysecretpassword')
class { 'yum' :
config_options => {
'proxy'          => 'https://host.example.com:3128',
'proxy_username' => 'user',
'proxy_password' => $secret,
},
}
}
```
I could add support for `Sensitive[Boolean]` and `Sensitive[Integer]` also if you think it is necessary, feel free to ask for it.  I was not sure it would be required.

Add sensitive support for configs

---

manifests/init.pp
spec/classes/init_spec.rb

The yum repository format should support entering multiple keys in the `gpgkey` entry, like the following entry for gitlab:
```
[gitlab_gitlab-ce]
name=gitlab_gitlab-ce
baseurl=https://packages.gitlab.com/gitlab/gitlab-ce/el/8/$basearch
repo_gpgcheck=1
gpgcheck=1
enabled=1
gpgkey=https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey
https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey/gitlab-gitlab-ce-3D645A26AB9FBD22.pub.gpg
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
```
Currently, this module only deploy the first gpgkey it encounter.  This change allow to deploy multiples gpg keys (separated by any white spaces), for example:
```
class { 'yum' :
managed_repos => ['gitlab'],
gpgkeys       => {
'/etc/pki/rpm-gpg/RPM-GPG-KEY-gitlab'                  => { …
```

Deploying multiple gpgkey in one repo

---

README.md

The `target` parameter is not implemented yet, so it doesn't do anything, and the yumrepo docs say not to use it: https://github.com/puppetlabs/puppetlabs-yumrepo_core/blob/136ee930eda907171a76fd599846f62602bec685/REFERENCE.md?plain=1#L349
See also: https://github.com/puppetlabs/puppetlabs-yumrepo_core/pull/47

README: remove yumrepo.target in example

---

manifests/init.pp
spec/classes/init_spec.rb

This method of purging unmanaged yum repo configs does not work. This is because the repo configs are managed by puppetlabs/yumrepo_core as native `yumrepo` types, not `file` resources.
Fixes #285

Revert #258, which added purge_unmanaged_repos

---

data/os/RedHat.yaml
spec/classes/init_spec.rb

Since AlmaLinux 9 is already in metadata.json, I think this doesn't require any additional changes
But, technically, I don't see why this won't work on RHEL9 and Rocky 9, unless testing suites are not ready yet
a side-note - ScientificLinux never released v8

add missing RPM-GPG-KEY-EPEL-9

---

REFERENCE.md
data/common.yaml
data/package_provider/dnf.yaml
manifests/config.pp
manifests/settings.pp
spec/acceptance/define_versionlock_spec.rb
spec/acceptance/yum_config_variable_false_spec.rb
spec/defines/config_spec.rb

Currently the augeas path for main configuration is at `/files/etc/yum.conf/main`.
Use a dnf or yum based path based on the package_provider fact.
On Fedora 36 and newer that hard coded augeas path does not exist:
```
[steve@fedora ~]$ augtool -e 'print /files/etc/yum.conf/main'
augtool> print /files/etc/yum.conf/main
```
only the new updated dnf based path exists.
```
augtool> print /files/etc/dnf/dnf.conf
/files/etc/dnf/dnf.conf
/files/etc/dnf/dnf.conf/#comment = "see `man dnf.conf` for defaults and possible options"
/files/etc/dnf/dnf.conf/main
/files/etc/dnf/dnf.conf/main/gpgcheck = "True"
/files/etc/dnf/dnf.conf/main/installonly_limit = "3"
/files/etc/dnf/dnf.conf/main/clean_requirements_on_remove = "True"
/files/etc/dnf/dnf.conf/main/best = "False" …
```

Use dnf or yum augeas path for main configuration

---

spec/acceptance/define_versionlock_spec.rb

With new versions of DNF
```
dnf -q list --available samba-devel
```
still shows samba-devel as available even when a non matching  versionlock exists. This looks to be by design.
Attempting to and failing to install the package is better validation anyway.
* https://bugzilla.redhat.com/show_bug.cgi?id=1746562#c1

Fix acceptance tests for Fedora 36

---

manifests/init.pp
spec/acceptance/yum_config_install_limit_2_spec.rb
spec/classes/init_spec.rb

Previously when `installonly_limit` of a node is adjusted then `package-cleanup` was called to remove unwanted old kernels. This is invalid for dnf based systems and a new command must be used.
This DNF command will remove kernel packages except in two cases:
* It is the running kernel as determined from `$facts['kernelrelease']`
* It is one of last N kernel versions where N is the `installonly_limit`
Fixes #295

Fix purge of unwanted kernels on DNF based machines

---

data/os/RedHat/AlmaLinux/9.yaml
spec/classes/init_spec.rb

```
almalinux-appstream.repo:[appstream-debuginfo]
almalinux-baseos.repo:[baseos-debuginfo]
almalinux-crb.repo:[crb-debuginfo]
almalinux-extras.repo:[extras-debuginfo]
almalinux-highavailability.repo:[highavailability-debuginfo] almalinux-nfv.repo:[nfv-debuginfo]
almalinux-plus.repo:[plus-debuginfo]
almalinux-resilientstorage.repo:[resilientstorage-debuginfo] almalinux-rt.repo:[rt-debuginfo]
almalinux-sap.repo:[sap-debuginfo]
almalinux-saphana.repo:[saphana-debuginfo]
```

Almalinux 9.2 shows these repos as `-debuginfo`

---

REFERENCE.md
manifests/init.pp
spec/acceptance/define_group_spec.rb
spec/classes/init_spec.rb

A hash of Yum groups can now be managed easily from hiera:
```yaml
---
yum::groups:
'Puppet Dev':
ensure: installed
'Rpm Dev':
ensure: absent
```
the existing `yum::group` defined type is used.
Fixes #305

New yum::groups parameter to manage groups

---

README.md
REFERENCE.md
manifests/copr.pp
spec/defines/copr_spec.rb

COPR (Cool Other Package Repo) is a Fedora project for third-party package repositories, see:
https://copr.fedorainfracloud.org/
This PR adds support to manage COPR repositories via a new `yum::copr` resource. 
Documentation and test are included. 
Fixes #149

Add yum::copr resource to handle COPR repositories.

---

README.md
REFERENCE.md
lib/puppet/provider/dnf_module_stream/dnf_module_stream.rb
lib/puppet/type/dnf_module_stream.rb
spec/acceptance/post_transaction_actions_spec.rb
spec/classes/plugin_post_transaction_actions_spec.rb
spec/unit/puppet/provider/dnf_module_stream/dnf_module_stream_spec.rb
spec/unit/puppet/type/dnf_module_stream_spec.rb

This PR adds a custom resource to freely enable/disable streams in DNF modules. The provider supports 4 different stream spec formats:
- `:default` - Enables default stream
- `:present` - Enables default stream if no stream is enabled, otherwise keep currently enabled one
- `:absent` - Disables current enabled stream, if any (that is: resets the module)
- `<String>` - Enables specified stream
Fixes #310
WIP: though it passes the very limited spec tests and my manual tests, I pushed this in a hurry. Need to review later without tired eyes.

Support dnf module management - Fix #310

---

manifests/versionlock.pp

Rebased @foxxx0 commit against master (see https://github.com/voxpupuli/puppet-yum/pull/228)
We're using his feature branch internally with RHEL 8 and RHEL 9 for about 2 years.
---
As stated in the manpage [1] yum versionlock supports package-wildcard
and does not require exact matches for package-names.
The following is valid `versionlock.list` content:
```
libvirt*-0:7.6.0-*.*
qemu*-0:6.1.0-*.*
```
This commit swaps `Yum::RpmName` with `Yum::RpmNameGlob` for the
versionlock `assert_type()` and thus allowing the above mentioned
examples.
[1] https://man7.org/linux/man-pages/man1/yum-versionlock.1.html

allow RpmNameGlob for versionlock entries

---

manifests/copr.pp
spec/acceptance/copr_spec.rb
spec/defines/copr_spec.rb

Improve yum::copr idempotency

---

lib/facter/yum_reboot_required.rb
lib/facter/yum_updates.rb
spec/unit/facter/yum_package_updates_spec.rb

Replace legacy facts

---

REFERENCE.md
manifests/group.pp
spec/acceptance/define_group_spec.rb
spec/defines/group_spec.rb

This adds support for dnf5, which no longer supports the old syntax. This will probably break support for rhel6 and lower. rhel7 already supports this syntax.
Fixes #338

Add support for dnf5

---

REFERENCE.md
manifests/init.pp
spec/classes/init_spec.rb

Provide a parameter to deploy plugin config elements.
Fixes #254

Add place to seed post_transaction_actions and versionlocks
